### ISSUE TITLE
What tensorflow framework used?

### ISSUE THREAD

**Issue by vgopinath** [jayita13/PHOENIX#2]
Hi,

I'm trying to make this code work. what TF framework version this code uses?

Regards

Gopi

**Comment by jayita13** [comment]
Hi gopi
I've used tf 2.2.0

**Comment by vgopinath** [comment]
Thanks, after creating a new conda environment with tf 2.2 the issue is fixed. Code works very well.

**Comment by bilel41213** [comment]
Hi,
what  version of python did you used.

**Comment by bilel41213** [comment]
Hi,
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\ASUS\.conda\envs\tf\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\ASUS\.conda\envs\tf\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "phoenix.py", line 48, in mainx
    loading()
  File "phoenix.py", line 31, in loading
    rootx.iconbitmap(default='IMAGES/home.ico')
  File "C:\Users\ASUS\.conda\envs\tf\lib\tkinter\__init__.py", line 1869, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: bitmap "IMAGES/home.ico" not defined

[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (415) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

**Comment by jayita13** [comment]
Hi @bilel41213 
I've used Python 3.6
Please make sure to have the required files accordingly as you run the phoenix.py file along with other required libraries I've mentioned

**Comment by bilel41213** [comment]
Tensor flow 2.3مرسل من هاتف Samsung Galaxy الذكي.

**Comment by mihirpaw** [comment]
please ,can you tell me the exact steps i should take to run this project , i.e. from installation to importing files and how to run the project. And also if some files are missing or not . I know i am asking a lot , but please do tell

**Comment by jayita13** [comment]
Hi @mihirpaw 
Firstly you can clone the repo (wherein all files are included) & install necessary libraries mentioned in the repo
you can download the model weights from here ->[https://pjreddie.com/media/files/yolov3.weights]

**Comment by jayita13** [comment]
Closed due to inactivity. Reopen if issue faced again
